name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Register Nuget packages
      env:
        telerik_username: ${{ secrets.TELERIK_USERNAME }}
        telerik_password: ${{ secrets.TELERIK_PASSWORD }}
      run: dotnet nuget add source https://nuget.telerik.com/v3/index.json --name telerik.com --username "$telerik_username" --password "$telerik_password"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
